### PR TITLE
Implement a better way to deal with 4-way-only controls

### PR DESCRIPTION
**Pull request by eniva**
There's more intuitive and responsive way to deal with 4-way-only controls.

For more details, please check out: https://github.com/eniva/fpga-controls

### CODE REVIEW

**Comment by sorgelig** [comment]
Make simple thing complex is not a good direction. 4-Way is already implemented in most useful way (Change direction in your terms). If you found the bug then welcome to correct it directly in existing code.
Btw, links to other repositories (submodules) are not accepted.

**Comment by eniva** [comment]
> 
> 
> Make simple thing complex is not a good direction. 4-Way is already implemented in most useful way (Change direction in your terms). If you found the bug then welcome to correct it directly in existing code.
> Btw, links to other repositories (submodules) are not accepted.

MsPacman and other 4-way cores don't seem to behave like "Change Direction" at all, sadly. An easy way to check this is to hold right and then press up (diagonal). Without my implementation, Ms. Pacman would not move up. I also tried your new joyonedir implementation on some newer cores, but they behave even worse (e.g. Donkey Kong's Jumpman/Mario will no longer move from horizontal -> up (diagonal) -> horizontal), while my implementation makes him move again.

Dealing with diagonals is strongly a preference issue that I think users should be able to choose how they want their diagonals to be processed. I would also force one way, but I just didn't want to make that decision for the users.

Would you reconsider this?

**Comment by sorgelig** [comment]
i'm not against the fix. 
I just think it can be a single entity/module dealing with change direction. I don't think it needs a special setting for that.

**Comment by sorgelig** [comment]
probably some arcades waiting for central position before it starts to react on other directions. Pacman is not intended to play like holding down the direction. It controlled by short presses in exact time to change the direction.

**Comment by eniva** [comment]
I understand your concern that little things like this can add up, but I believe this is something we should really consider giving the user the power to control how it should be handled.

The reason why I added the user setting is because there's a big split in how people want their diagonals to be handled. Especially for games like Tetris, among those who do not use 4-way joystick, it's usually Change Direction vs. Stop. I hate forcing one option on users.

People have different grips and the way they handle their 8-way joysticks, which is why I decided to provide the settings. For example, standard Korean joysticks use round-gates. These joysticks are likely to send the 4way properly with diagonals often pressed by accident ever so slightly after. For these sticks, Keep Direction is a lot more preferred for them. Although I don't use Korean joysticks, it just seemed unfair to force them use the Change Direction method.

If you're still against providing a user option, I will force it to Change Direction, remove the submodule entirely and just add in files. However, I really hope you see why the option is necessary and keeps the spirit of providing a fix for diagonals and reconsider the special setting.

If you're also against having multiple modules, I should be able to hardcode everything within a single module. This was designed to be very modular, but I can follow how you want your project modules to be organized.

**Comment by sorgelig** [comment]
There is some inconvenience with some arcades because can press 2 directions at the same time. So the solution is targeted only for this problem - nothing more. Need to understand not all arcades really need this correction.
Generally speaking even this arcade not really need it as it can be played after some tries. Arcade cabinet should use + template if user really want it to be played as on original HW. So, problem is exaggerated.

**Comment by eniva** [comment]
I will just force Change Direction, remove user options and remove the link to create a new pull request. Thanks.

**Pull request closed without merging**
